// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_lite_messages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW0zsqenIj4fGWMHNTpZg_9hU8dZjsS5U',
    appId: '1:205572842828:web:f940ec7a8ddeb395615be9',
    messagingSenderId: '205572842828',
    projectId: 'sye26-investment',
    authDomain: 'sye26-investment.firebaseapp.com',
    storageBucket: 'sye26-investment.firebasestorage.app',
    measurementId: 'G-1QNSG6K4PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_4s-ExxncJC1BFxWEdkMQ2rc_396dT0E',
    appId: '1:205572842828:android:69806eccf2f7a1f5615be9',
    messagingSenderId: '205572842828',
    projectId: 'sye26-investment',
    storageBucket: 'sye26-investment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDilEoj_g4WSgjFM-8W6JLcUcybWhjtF-Y',
    appId: '1:205572842828:ios:5c99c671d6b30fa7615be9',
    messagingSenderId: '205572842828',
    projectId: 'sye26-investment',
    storageBucket: 'sye26-investment.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDilEoj_g4WSgjFM-8W6JLcUcybWhjtF-Y',
    appId: '1:205572842828:ios:5c99c671d6b30fa7615be9',
    messagingSenderId: '205572842828',
    projectId: 'sye26-investment',
    storageBucket: 'sye26-investment.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: '1:1234567890:web:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'final-project-dummy',
    authDomain: 'final-project-dummy.firebaseapp.com',
    storageBucket: 'final-project-dummy.appspot.com',
  );
}